import React from 'react';
import { View, StyleSheet } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { ShieldCheck, Sparkles, TriangleAlert } from 'lucide-react-native';
import { radius, space } from '../tokens';
import { useTheme } from '../theme';
import { Text } from './Text';
import { Card } from './Surface';

/**
 * The disclosure that must appear on every screen capable of a cloud call
 * (spec §5.2, §9.1). Copy is passed in so it can state the *resolved* provider
 * and model rather than a hard-coded string.
 */
export function PrivacyNote({ children }: { children: string }) {
  const t = useTheme();
  return (
    <Card
      fill="sunken"
      style={{ flexDirection: 'row', gap: space.sm, alignItems: 'flex-start' }}
      accessibilityRole="summary"
      accessibilityLabel={`Privacy notice. ${children}`}
    >
      <ShieldCheck size={18} color={t.colors.accent} style={{ marginTop: 2 }} />
      <Text variant="caption" tone="soft" style={{ flex: 1 }}>
        {children}
      </Text>
    </Card>
  );
}

/** Mandatory label on any AI output surface (spec §9.1, onboarding step 6). */
export function AIGeneratedLabel({ model }: { model: string }) {
  const t = useTheme();
  return (
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
      <Sparkles size={13} color={t.colors.inkMuted} />
      <Text variant="caption" tone="muted">
        AI-generated by {model}. General information, not medical advice.
      </Text>
    </View>
  );
}

export type PillTone = 'removed' | 'kept' | 'caution' | 'neutral' | 'accent';

export function Pill({ label, tone = 'neutral' }: { label: string; tone?: PillTone }) {
  const t = useTheme();
  const map = {
    removed: [t.colors.removedBg, t.colors.removedFg],
    kept: [t.colors.keptBg, t.colors.keptFg],
    caution: [t.colors.cautionBg, t.colors.cautionFg],
    accent: [t.colors.accentSoft, t.colors.accent],
    neutral: [t.colors.surfaceSunken, t.colors.inkSoft],
  }[tone];
  return (
    <View
      style={{
        paddingHorizontal: space.sm,
        paddingVertical: 6,
        borderRadius: radius.chip,
        backgroundColor: map[0],
      }}
    >
      <Text variant="eyebrow" style={{ color: map[1] }} maxScale={1.4}>
        {label.toUpperCase()}
      </Text>
    </View>
  );
}

/**
 * Activity ring. Renders an empty track with a dot marker when `value` is null
 * — the spec forbids showing a fabricated number, so "no data" reads as "–".
 */
export function MetricRing({
  value,
  goal,
  glyph,
  label,
  formatted,
}: {
  value: number | null;
  goal: number;
  glyph: React.ReactNode;
  label: string;
  formatted: string;
}) {
  const t = useTheme();
  const size = 66;
  const stroke = 5;
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  const pct = value == null ? 0 : Math.min(value / goal, 1);

  return (
    <View
      style={{ alignItems: 'center', gap: 6 }}
      accessible
      accessibilityRole="progressbar"
      accessibilityLabel={label}
      accessibilityValue={{ text: value == null ? 'No data yet' : formatted }}
    >
      <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}>
        <Svg width={size} height={size} style={StyleSheet.absoluteFill}>
          <Circle
            cx={size / 2}
            cy={size / 2}
            r={r}
            stroke={t.colors.surfaceSunken}
            strokeWidth={stroke}
            fill="none"
          />
          {pct > 0 && (
            <Circle
              cx={size / 2}
              cy={size / 2}
              r={r}
              stroke={t.colors.accent}
              strokeWidth={stroke}
              strokeLinecap="round"
              strokeDasharray={`${c * pct} ${c}`}
              transform={`rotate(-90 ${size / 2} ${size / 2})`}
              fill="none"
            />
          )}
        </Svg>
        {glyph}
      </View>
      <Text variant="title">{formatted}</Text>
      <Text variant="eyebrow" tone="muted" maxScale={1.4}>
        {label}
      </Text>
    </View>
  );
}

/** Onboarding pagination — current step widens into a bar rather than changing colour only. */
export function ProgressDots({ count, index }: { count: number; index: number }) {
  const t = useTheme();
  return (
    <View
      style={{ flexDirection: 'row', gap: 7, alignItems: 'center' }}
      accessibilityRole="progressbar"
      accessibilityLabel={`Step ${index + 1} of ${count}`}
    >
      {Array.from({ length: count }).map((_, i) => (
        <View
          key={i}
          style={{
            height: 7,
            width: i === index ? 26 : 7,
            borderRadius: 4,
            backgroundColor:
              i <= index ? t.colors.accent : t.colors.border,
            opacity: i < index ? 0.7 : 1,
          }}
        />
      ))}
    </View>
  );
}

/** Blocking safety banner. Used for emergency routing and conflict resolution. */
export function SafetyBanner({ title, body }: { title: string; body: string }) {
  const t = useTheme();
  return (
    <Card
      style={{
        borderWidth: 1.5,
        borderColor: t.colors.removedFg,
        backgroundColor: t.colors.removedBg,
        gap: space.xs,
      }}
      accessibilityRole="alert"
    >
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: space.xs }}>
        <TriangleAlert size={18} color={t.colors.removedFg} />
        <Text variant="title" style={{ color: t.colors.removedFg, flex: 1 }}>
          {title}
        </Text>
      </View>
      <Text variant="body" tone="ink">
        {body}
      </Text>
    </Card>
  );
}
